services:
  meeting_db:
    image: postgres:16
    container_name: meeting_db
    environment:
      POSTGRES_USER: navis
      POSTGRES_PASSWORD: navis@123
      POSTGRES_DB: meetingdb
    volumes:
      - meeting_db_data:/var/lib/postgresql/data
    networks:
      - meeting_network
    restart: unless-stopped

  meeting_backend:
    build: .
    container_name: meeting_backend
    ports:
      - "8080:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      ConnectionStrings__DefaultConnection: "Host=meeting_db;Port=5432;Database=meetingdb;Username=navis;Password=navis@123"
    depends_on:
      - meeting_db
    networks:
      - meeting_network
    restart: unless-stopped

networks:
  meeting_network:
    driver: bridge

volumes:
  meeting_db_data:
